spring:
  application:
    name: composite

# register your app in google at following address:
# https://console.developers.google.com/apis/credentials
# redirect Url must be set to: http://localhost:8080/login/google


# register your app in github at following address:
# https://github.com/settings/developers




